/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.eng.moretto.arduinoturbo;

import br.eng.moretto.arduinoturbo.ui.CellRenderer;
import java.awt.Color;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Enumeration;
import java.util.Properties;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.TableModel;
import sun.util.ResourceBundleEnumeration;

/**
 *
 * @author oper
 */
public class Main extends javax.swing.JFrame {

    SerialTest serial;
    
    Properties props = new Properties();
       
    static final String MAP_FILE = "map01.properties";
    
    
    int mapWidth = 15;
    int mapHeight = 15;
    int maxRPM = 7000;
    
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
                
        loadMaps();
        
        createTable();
        
    }

    private void loadMaps(){
        
        try{            
            mapList.removeAll();
            //props.load(Main.class.getClassLoader().getResourceAsStream(MAP_FILE));            
            props.load(new FileInputStream("/Users/oper/github/local/ArduinoTurbo-Java/Mapper/resources/map01.properties"));
                        
            Enumeration<Object> e = props.keys();
            while(e.hasMoreElements()){
                mapList.add((String) e.nextElement());
            }                            
        }catch(Exception e){
            e.printStackTrace();
        }
        
        
    }
    
    private void createTable(){
        
        // Creating table
        String[] columnNames = new String[mapWidth];
        Integer[][] data = new Integer[mapWidth][mapHeight];       
        
        
        int factor = 500;//(int) maxRPM / mapWidth;       
        
        for(int i=0 ; i < mapWidth ; i++){            
            columnNames[i] = ""+(i * factor);
            for(int j=0 ; j < mapHeight ; j++){            
                data[i][j] = 0;
            }
        }
        
        jTable1.setModel(new javax.swing.table.DefaultTableModel(data,columnNames));
        jTable1.setDefaultRenderer(Integer.class, new CellRenderer(true));
                
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        trafficLight1 = new eu.hansolo.steelseries.extras.TrafficLight();
        textAreaOutput = new java.awt.TextArea();
        connectSerialButton = new java.awt.Button();
        textField1 = new java.awt.TextField();
        sendButton = new java.awt.Button();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        loadTable = new javax.swing.JButton();
        mapList = new java.awt.List();
        saveButton = new javax.swing.JButton();
        disconnectSerialButton = new java.awt.Button();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        trafficLight1.setRedOn(true);

        org.jdesktop.layout.GroupLayout trafficLight1Layout = new org.jdesktop.layout.GroupLayout(trafficLight1);
        trafficLight1.setLayout(trafficLight1Layout);
        trafficLight1Layout.setHorizontalGroup(
            trafficLight1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 26, Short.MAX_VALUE)
        );
        trafficLight1Layout.setVerticalGroup(
            trafficLight1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 116, Short.MAX_VALUE)
        );

        connectSerialButton.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        connectSerialButton.setForeground(new java.awt.Color(0, 102, 153));
        connectSerialButton.setLabel("Connect");
        connectSerialButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectSerialButtonActionPerformed(evt);
            }
        });

        textField1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        textField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField1ActionPerformed(evt);
            }
        });

        sendButton.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        sendButton.setLabel("Send");
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Título 1"
            }
        ));
        jTable1.setShowGrid(true);
        jScrollPane1.setViewportView(jTable1);

        loadTable.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        loadTable.setText("Load Map");
        loadTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadTableActionPerformed(evt);
            }
        });

        saveButton.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        saveButton.setText("Save Map");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        disconnectSerialButton.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        disconnectSerialButton.setForeground(new java.awt.Color(0, 102, 153));
        disconnectSerialButton.setLabel("Disconnect");
        disconnectSerialButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disconnectSerialButtonActionPerformed(evt);
            }
        });

        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n14\n15");
        jScrollPane2.setViewportView(jTextArea1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(textAreaOutput, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 655, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(trafficLight1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 26, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(saveButton)
                    .add(layout.createSequentialGroup()
                        .add(textField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 410, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(sendButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(connectSerialButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(disconnectSerialButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 38, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 826, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(loadTable)
                            .add(mapList, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 128, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(connectSerialButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(disconnectSerialButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(mapList, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(loadTable, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 365, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 345, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(saveButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(sendButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .add(textField1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(textAreaOutput, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 184, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(trafficLight1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 116, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        disconnectSerialButton.getAccessibleContext().setAccessibleName("Disconnect");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void connectSerialButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectSerialButtonActionPerformed

        serial = new SerialTest(textAreaOutput);
        serial.initialize();
        /*
        Thread t=new Thread() {
                public void run() {
                        //the following line will keep this app alive for 1000 seconds,
                        //waiting for events to occur and responding to them (printing incoming messages to console).
                        try {Thread.sleep(10000000);} catch (InterruptedException ie) {}
                }
        };
        t.start();
        */
        trafficLight1.setRedOn(false);
        trafficLight1.setGreenOn(true);
        System.out.println("Started");
                
                
                
    }//GEN-LAST:event_connectSerialButtonActionPerformed

    private String buildStringMap(){
        
        TableModel model = jTable1.getModel();
        StringBuilder result = new StringBuilder();

        
        for(int i=0 ; i < mapWidth ; i++){

            for(int j=0 ; j < mapHeight ; j++){
                result.append(model.getValueAt(i, j));
                
                if(j != mapHeight) result.append(",");                
            }
            result.append(";");
        }
        return result.toString();
    }
    
    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed

        //textField1.setText(result.toString());
        serial.write("m"+buildStringMap());
        
    }//GEN-LAST:event_sendButtonActionPerformed

    private void textField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField1ActionPerformed

    private void loadTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadTableActionPerformed

        createTable();
        
        if(mapList.getSelectedIndex() >= 0){
        
            TableModel model = jTable1.getModel();

            String[] rows = props.getProperty(mapList.getSelectedItem()).split(";");

            for(int i=0 ; i < mapWidth ; i++){
                for(int j=0 ; j < mapHeight ; j++){
                    model.setValueAt(Integer.parseInt(rows[i].split(",")[j]), i, j);
                }
            }
        }
        
        
    }//GEN-LAST:event_loadTableActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed

        String map = buildStringMap();
        
        String mapName = JOptionPane.showInputDialog ("Map name" , mapList.getSelectedItem()); 
        
        if(mapName != null){
            System.out.println(mapName);
            //TODO: save!
            //Persistence.getInstance().set(mapName, map);
            props.setProperty(mapName, map);
           
            try {
                System.out.println(Main.class.getClassLoader().getResource(MAP_FILE).getPath());
                //save properties to project root folder
                //props.store(new FileOutputStream(Main.class.getClassLoader().getResource(MAP_FILE).getPath()), null);
                props.store(new FileOutputStream("/Users/oper/github/local/ArduinoTurbo-Java/Mapper/resources/map01.properties"),null);
                
                        
                loadMaps();
                
            } catch (IOException ex) {
               
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
                        
        }
        
    }//GEN-LAST:event_saveButtonActionPerformed

    private void disconnectSerialButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disconnectSerialButtonActionPerformed
        
        serial.close();
        
        trafficLight1.setRedOn(true);
        trafficLight1.setGreenOn(false);        
        
    }//GEN-LAST:event_disconnectSerialButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button connectSerialButton;
    private java.awt.Button disconnectSerialButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton loadTable;
    private java.awt.List mapList;
    private javax.swing.JButton saveButton;
    private java.awt.Button sendButton;
    private java.awt.TextArea textAreaOutput;
    private java.awt.TextField textField1;
    private eu.hansolo.steelseries.extras.TrafficLight trafficLight1;
    // End of variables declaration//GEN-END:variables
}
